### ISSUE TITLE
Multiple kmx files?

### ISSUE THREAD

**Issue by kiragecko** [keymanapp/keyboards-starter#6]
Hello,

I'm experiencing an odd error message when I try to build my project.  I'm being told that there should only be 1 .kmx file in the package, and as far as I can tell, I only have 1...

https://github.com/kiragecko/keyboards-starter

```
$ ./build.sh IPAKeyboard
Building IPAKeyboard
Building keyboard IPAKeyboard/release/i/IPAKeyboard

IPAKeyboard.kmn: Compiling D:\IPAKeyboard\keyboards-starter\IPAKeyboard\release\i\IPAKeyboard\source\IPAKeyboard.kmn for Windows, MacOSX...
IPAKeyboard.kmn: 'D:\IPAKeyboard\keyboards-starter\IPAKeyboard\release\i\IPAKeyboard\source\IPAKeyboard.kmn' compiled successfully for Windows to 'D:\IPAKeyboard\keyboards-starter\IPAKeyboard\release\i\IPAKeyboard\build\IPAKeyboard.kmx'.
IPAKeyboard.kps: Compiling package IPAKeyboard.kps...
IPAKeyboard.kps: 'D:\IPAKeyboard\keyboards-starter\IPAKeyboard\release\i\IPAKeyboard\source\IPAKeyboard.kps' compiled successfully to 'D:\IPAKeyboard\keyboards-starter\IPAKeyboard\release\i\IPAKeyboard\build\IPAKeyboard.kmp'.
Merging IPAKeyboard.keyboard_info for IPAKeyboard
Memory 0: 00000000 Invalid .keyboard_info file: There should be exactly 1 .kmx file in the package.
Failed to merge keyboard_info for IPAKeyboard.keyboard_info
Aborting with error 1

```

**Comment by darcywong00** [comment]
In your keyboard package source file [IPAKeyboard.kps](https://github.com/kiragecko/keyboards-starter/blob/master/IPAKeyboard/release/i/IPAKeyboard/source/IPAKeyboard.kps), 
you're including the keyboard source file (kmn) when it should be the compiled keyboard (kmx).

```
    <File>
      <Name>IPAKeyboard.kmn</Name>
      <Description>File IPAKeyboard.kmn</Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.kmn</FileType>
    </File>
```

I recommend organizing your project files according to this [guide](https://help.keyman.com/developer/keyboards/starter/step-3.php)

[Step 4](https://help.keyman.com/developer/keyboards/starter/step-4.php) describes configuring the keyboard project to put compiler artifacts like the .kmx file into a `build/` folder. In your case, it would go in `keyboards-starter/ipkeyboard/release/i/ipakeyboard/build/`

**Comment by kiragecko** [comment]
I have applied the feedback in the file you mentioned.  Also, I have tried to follow the organization system mentioned in the guide... Is there something I missed?

I also rebased my changes on to the latest version of this repository.

Unfortunately, my problem hasn't changed.

**Comment by darcywong00** [comment]
In your `source\IPAKeyboard.kps` Keyman package file, you've only included the `ipaWE.ico` icon file, so you'll still need to add the compiled `build\IPAKeyboard.kmx` keyboard.

Refer to the [Package tutorial](https://help.keyman.com/developer/10.0/guides/distribute/tutorial/) for a recommend list of files to include.

**Comment by vicp-iq** [comment]
That resolved the error.  Thank you for your help!

**Comment by darcywong00** [comment]
> That resolved the error. Thank you for your help!

You're welcome. 

Future issues can be posted on the Keyman Community site
https://community.software.sil.org/c/keyman 

where other users can chime in and help.
